from django.conf import settings
from django.db import models

from apps.core.models import BaseModel


class PalateProfile(BaseModel):
    """
    Stores a user's structured taste profile generated by Claude from
    their tasting notes and visit history. The pinecone_vector_id links
    to the embedding in Pinecone for semantic search.
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="palate_profile"
    )

    # Structured preferences (generated by Claude)
    preferences = models.JSONField(
        default=dict,
        blank=True,
        help_text="Structured palate profile: sweetness, acidity, body, tannins, flavor_notes, etc.",
    )

    # Pinecone vector for semantic similarity search
    pinecone_vector_id = models.CharField(max_length=255, blank=True, db_index=True)

    # Track when the profile was last analyzed
    last_analyzed_at = models.DateTimeField(null=True, blank=True)
    analysis_version = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = "palate_palateprofile"

    def __str__(self):
        return f"Palate — {self.user}"
