# Generated by Django 6.0.3 on 2026-03-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Partner tier from Lookup: PARTNER_TIER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_by_tier', to='lookup.lookupvalue'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.ForeignKey(blank=True, help_text='Promotion type from Lookup: PROMOTION_TYPE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_by_type', to='lookup.lookupvalue'),
        ),
    ]
