# Generated by Django 6.0.3 on 2026-03-20 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_lookup_tier_and_promotion_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.CreateModel(
            name='PartnerOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Owner'), ('owner', 'Owner'), ('manager', 'Manager')], default='owner', max_length=20)),
                ('title', models.CharField(blank=True, help_text='e.g. CEO, Head Winemaker', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_owners', to='partners.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners_partnerowner',
                'ordering': ['role', 'user__first_name'],
                'unique_together': {('partner', 'user')},
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='owners',
            field=models.ManyToManyField(related_name='partner_memberships', through='partners.PartnerOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
