# Generated by Django 6.0.3 on 2026-03-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_add_partner_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerowner',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='partnerowner',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partnerowner',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='partnerowner',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partnerowner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
