# Generated by Django 6.0.3 on 2026-03-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_add_owner_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='subscription_plan',
            field=models.CharField(blank=True, help_text='e.g. silver_monthly, gold_yearly', max_length=30),
        ),
        migrations.AddField(
            model_name='partner',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'None'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='free', max_length=20),
        ),
    ]
