# Generated by Django 6.0.3 on 2026-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='travel_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Drive time from previous stop', null=True),
        ),
    ]
