# Generated by Django 6.0.3 on 2026-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripwinery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tripwinery',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripwinery',
            name='meeting_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tripwinery',
            name='travel_details',
            field=models.TextField(blank=True),
        ),
    ]
