# Generated by Django 6.0.3 on 2026-03-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripwinery_description_tripwinery_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trip',
            name='meeting_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='transportation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
