# Generated by Django 6.0.3 on 2026-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_add_travel_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='travel_miles',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance from previous stop in miles', max_digits=6, null=True),
        ),
    ]
