# Generated by Django 6.0.3 on 2026-03-22 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_add_travel_miles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SippyConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_type', models.CharField(choices=[('ask', 'Ask Sippy'), ('plan', 'Plan with Sippy')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('messages', models.JSONField(default=list)),
                ('phase', models.CharField(blank=True, default='', max_length=20)),
                ('proposed_trip', models.JSONField(blank=True, default=dict)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sippy_conversations', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sippy_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips_sippyconversation',
                'ordering': ['-updated_at'],
            },
        ),
    ]
