# Generated by Django 6.0.3 on 2026-03-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_sippy_conversation'),
        ('visits', '0004_add_rating_comments_to_visitwine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_stop', to='visits.visitlog'),
        ),
    ]
