# Generated by Django 6.0.3 on 2026-03-18 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWinery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_wineries', to=settings.AUTH_USER_MODEL)),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='wineries.winery')),
            ],
            options={
                'db_table': 'wineries_favoritewinery',
                'unique_together': {('user', 'winery')},
            },
        ),
    ]
