# Generated by Django 6.0.3 on 2026-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
