# Generated by Django 6.0.3 on 2026-03-22 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineries', '0002_add_place_zip_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WineWishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wine_name', models.CharField(max_length=255)),
                ('wine_type', models.CharField(blank=True, max_length=100)),
                ('wine_vintage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlisted_by', to='wineries.menuitem')),
                ('source_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_sources', to='wineries.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places_winewishlist',
                'ordering': ['-created_at'],
            },
        ),
    ]
