from django.urls import path

from apps.trips.views import (
    LiveTripAdvanceView,
    LiveTripCheckinView,
    LiveTripCompleteView,
    LiveTripUndoCheckinView,
    LiveTripRateView,
    LiveTripView,
    LiveTripWineMenuView,
    LiveTripWineView,
    QuickCheckinView,
    QuickTripView,
    TripAddStopView,
    TripCopyView,
    TripCreateView,
    TripDeleteView,
    TripDetailView,
    TripInviteView,
    TripListView,
    TripRemoveMemberView,
    TripRemoveStopView,
    TripReorderStopsView,
    TripStopsPartialView,
    TripUpdateMemberView,
    TripUpdateStopView,
    TripUpdateView,
)

urlpatterns = [
    path("", TripListView.as_view(), name="trip_list"),
    path("plan/", TripCreateView.as_view(), name="trip_create"),
    path("quick/", QuickTripView.as_view(), name="trip_quick"),
    path("checkin/", QuickCheckinView.as_view(), name="quick_checkin"),
    path("<uuid:pk>/copy/", TripCopyView.as_view(), name="trip_copy"),
    path("<uuid:pk>/", TripDetailView.as_view(), name="trip_detail"),
    path("<uuid:pk>/update/", TripUpdateView.as_view(), name="trip_update"),
    path("<uuid:pk>/delete/", TripDeleteView.as_view(), name="trip_delete"),
    path("<uuid:pk>/live/", LiveTripView.as_view(), name="trip_live"),
    path("<uuid:pk>/live/checkin/<uuid:stop_pk>/", LiveTripCheckinView.as_view(), name="trip_live_checkin"),
    path("<uuid:pk>/live/undo-checkin/<uuid:stop_pk>/", LiveTripUndoCheckinView.as_view(), name="trip_live_undo_checkin"),
    path("<uuid:pk>/live/rate/<uuid:visit_pk>/", LiveTripRateView.as_view(), name="trip_live_rate"),
    path("<uuid:pk>/live/wine/", LiveTripWineView.as_view(), name="trip_live_wine"),
    path("<uuid:pk>/live/wine-menu/<uuid:place_pk>/", LiveTripWineMenuView.as_view(), name="trip_live_wine_menu"),
    path("<uuid:pk>/live/advance/", LiveTripAdvanceView.as_view(), name="trip_live_advance"),
    path("<uuid:pk>/live/complete/", LiveTripCompleteView.as_view(), name="trip_live_complete"),
    path("<uuid:pk>/stops/", TripStopsPartialView.as_view(), name="trip_stops_partial"),
    path("<uuid:pk>/stops/add/", TripAddStopView.as_view(), name="trip_add_stop"),
    path("<uuid:pk>/reorder/", TripReorderStopsView.as_view(), name="trip_reorder"),
    path("<uuid:pk>/stops/<uuid:stop_pk>/update/", TripUpdateStopView.as_view(), name="trip_update_stop"),
    path("<uuid:pk>/stops/<uuid:stop_pk>/remove/", TripRemoveStopView.as_view(), name="trip_remove_stop"),
    path("<uuid:pk>/invite/", TripInviteView.as_view(), name="trip_invite"),
    path("<uuid:pk>/members/<uuid:member_pk>/update/", TripUpdateMemberView.as_view(), name="trip_update_member"),
    path("<uuid:pk>/members/<uuid:member_pk>/remove/", TripRemoveMemberView.as_view(), name="trip_remove_member"),
]
