# Generated by Django 6.0.3 on 2026-03-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stripe_customer_id_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='America/New_York', help_text='IANA timezone (e.g. America/New_York)', max_length=63),
        ),
    ]
