# Generated by Django 6.0.3 on 2026-03-19 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PalateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Structured palate profile: sweetness, acidity, body, tannins, flavor_notes, etc.')),
                ('pinecone_vector_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_version', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='palate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palate_palateprofile',
            },
        ),
    ]
