# Generated by Django 6.0.3 on 2026-03-19 21:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wineries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visited_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('rating_staff', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_ambience', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_food', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_overall', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='wineries.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visits_visitlog',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitWine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wine_name', models.CharField(blank=True, max_length=255)),
                ('wine_type', models.CharField(blank=True, max_length=100)),
                ('wine_vintage', models.PositiveIntegerField(blank=True, null=True)),
                ('serving_type', models.CharField(choices=[('tasting', 'Tasting'), ('glass', 'Glass'), ('flight', 'Flight'), ('bottle', 'Bottle'), ('split', 'Split')], default='tasting', max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tasting_notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('purchased', models.BooleanField(default=False)),
                ('purchased_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchased_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('purchased_notes', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='wineries.menuitem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines_tasted', to='visits.visitlog')),
            ],
            options={
                'db_table': 'visits_visitwine',
            },
        ),
    ]
