# Generated by Django 6.0.3 on 2026-03-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitwine',
            name='photo',
            field=models.TextField(blank=True, help_text='Photo URL or base64 data URI'),
        ),
    ]
