# Generated by Django 6.0.3 on 2026-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_add_visitwine_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitwine',
            name='serving_type',
            field=models.CharField(blank=True, default='tasting', max_length=50),
        ),
    ]
