# Generated by Django 6.0.3 on 2026-03-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_remove_serving_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitwine',
            name='rating_comments',
            field=models.TextField(blank=True),
        ),
    ]
